- .github/workflows/constraints.txt
- CONTRIBUTING.rst
- poetry.lock
Due to an bug with poetry 1.1.4 , Python 3.7 and export function.
> Downgrade to Poetry 1.0.10

- poetry.lock
- pyproject.toml
https://github.com/home-assistant/core/blob/dev/requirements.txt
> Pin aiohttp to 3.7.1 to match HA

- pyproject.toml
> Bump next to 0.0.1-alpha.1

- tests/fixtures/kamereon/error/access_denied.json
- tests/fixtures/kamereon/vehicles/zoe1_without_nav.json
ZOE phase 1 without navigation.
403 error when trying to have hvac_mode status.
contributes: #48
> Add fixtures from oncleben31

- src/renault_api/credential_store.py
- src/renault_api/kamereon.py
- tests/__init__.py
- tests/test_credential_store.py
Add CredentialStore/FileCredentialStore classes to be able to store the credentials in CLI mode
> Add CredentialStore

- .github/workflows/develop.yml
Clone of main/master CI but prevent auto-publish
> Add CI for develop branch

- src/renault_api/model/kamereon.py
- tests/fixtures/kamereon/vehicle_data/battery-status.2.json
- tests/fixtures/kamereon/vehicle_data/charge-mode.json
- tests/fixtures/kamereon/vehicle_data/location.json
- tests/model/test_kamereon_vehicle_data.py
Add chargingRemainingTime / chargingInstantaneousPower to KamereonVehicleBatteryStatusData
Add chargeMode to KamereonVehicleChargeModeData
Add lastUpdateTime / gpsLatitude / gpsLongitude to KamereonVehicleLocationData
> Add properties to Kamereon models

- src/renault_api/exceptions.py
- src/renault_api/renault_session.py
- tests/test_renault_session.py
- Introduce NotAuthenticatedException if authentication is required
- Ensure authentication token is cleared on some get_jwt errors
> Improve exception handling in RenaultSession

- src/renault_api/cli/renault_vehicle_charge.py
- src/renault_api/kamereon/enums.py
- src/renault_api/kamereon/models.py
- src/renault_api/renault_vehicle.py
- tests/kamereon/test_kamereon_vehicle_data.py
- tests/test_renault_vehicle.py
Drop ChargeMode enum
Update ChargeState
Update PlugState
> Update enums to match MyRenault app

- .gitignore
- src/renault_api/cli/__main__.py
- src/renault_api/cli/renault_vehicle_charge.py
- tests/cli/test_vehicle_charge.py
- tests/fixtures/kamereon/vehicle_data/charging-settings.json
- tests/kamereon/test_kamereon_vehicle_data.py
- tests/kamereon/test_kamereon_vehicle_schedule.py
> Fix CLI charge-settings schedule-id identification

- src/renault_api/cli/__main__.py
- src/renault_api/cli/helpers.py
- tests/cli/test_client.py
- tests/cli/test_main.py
> Auto-create CLI log folder

- .gitignore
- poetry.toml
To ease the project installation process for the developers, a nice feature of Poetry is to create a virtual env directly in the project.
See https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean
Most of the IDE automatically detects it and uses it.
Thanks @tetienne
> Update default virtual environment location

- poetry.lock
> Security update to py 1.10.0

- src/renault_api/kamereon/models.py
- src/renault_api/renault_vehicle.py
`KamereonVehiclesDetails` => `KamereonVehicleDetails`
`KamereonVehiclesDetailsGroup` => `KamereonVehicleDetailsGroup`
> Rename VehicleDetails models

- src/renault_api/kamereon/helpers.py
- tests/kamereon/test_kamereon_vehicle_action.py
Related to https://github.com/hacf-fr/hassRenaultZE/issues/110
> Add support for `activated` flag in `update_schedule`

- noxfile.py
Ignore tornado/39462 as there is currently no fix
See https://github.com/tornadoweb/tornado/issues/2981
> Update nox safety session

- README.rst
battery_status is undefined whereas get_battery_status is found on the vehicle.
> Update API usage documentation

- pyproject.toml
> Bump minimal version of aiohttp to 3.7.4.post0

- pyproject.toml
> Bump minimal version of PyJWT to 2.1.0

- src/renault_api/kamereon/models.py
- tests/cli/test_vehicle.py
- tests/fixtures.py
- tests/kamereon/test_kamereon_vehicle_details.py
> Enable hvac-status on TwingoZE

- src/renault_api/cli/renault_vehicle.py
> Cleanup has_contract in CLI

- src/renault_api/cli/renault_vehicle.py
- tests/cli/test_vehicle.py
New Edit from #532
Implements #531
> Adding --json support for status command

- poetry.lock
- pyproject.toml
Bump safety from 2.1.1 to 2.3.1
> Bump safety from 2.1.1 to 2.3.1

- src/renault_api/const.py
Ref: https://github.com/home-assistant/core/issues/91593
> Update default Kamereon API key

- .github/workflows/tests.yml
Cancel previous runs for the same PR or the same branch.
> Add concurrency to CI

- src/renault_api/cli/charge/history.py
- tests/cli/test_vehicle_charge.py
- tests/fixtures/kamereon/vehicle_data/charges-megane.json
> Add Energy gained column

- .github/workflows/release.yml
Reverts bc7eb04e28742c35e989f4590ce2f139bda0be1c
> Revert "Fix release CI (#943)"

- docs/endpoints/vehicle_action.charge-mode.rst
- docs/endpoints/vehicle_data.charge-mode.rst
> Update charge-mode documentation

- src/renault_api/kamereon/models.py
- tests/cli/test_vehicle.py
- tests/fixtures/kamereon/vehicle_data/hvac-status.spring.json
- tests/fixtures/kamereon/vehicle_data/hvac-status.zoe.json
- tests/fixtures/kamereon/vehicle_data/hvac-status.zoe_50.json
> Fix HVAC status endpoint

- src/renault_api/kamereon/enums.py
To fix https://github.com/hacf-fr/renault-api/issues/1262 ...hoping it is indeed the good state.
> Added unconfirmed plug state 3

- src/renault_api/kamereon/helpers.py
- src/renault_api/kamereon/models.py
- tests/kamereon/test_kamereon_vehicle_action.py
Extracted from #1301
cc @vhkristof
> Rename charge_schedule helpers

- src/renault_api/kamereon/models.py
Note: I can contribute with any missing information and tests.
> Add vehicle code XCB1SE for SCENIC E-TECH

- README.rst
Added command line examples (lik to command line help is not working)
> Add examples for raw http calls

- src/renault_api/kamereon/models.py
> Revert unconfirmed plug state 3

- src/renault_api/cli/renault_vehicle.py
- src/renault_api/kamereon/models.py
> Update code coverage configuration

- docs/endpoints.rst
- docs/endpoints/vehicle_data.soc-levels.rst
- src/renault_api/kamereon/models.py
- tests/__snapshots__/test_renault_vehicle.ambr
- tests/fixtures/kamereon/vehicle_data/kcm-ev-soc-levels.json
Draft as waiting for "real" fixture
> Add documentation and fixture for soc-levels endpoint

- docs/endpoints.rst
- docs/endpoints/vehicle_action.horn-lights.rst
> Add documentation for horn-lights action endpoint

- src/renault_api/kamereon/models.py
- src/renault_api/renault_vehicle.py
- tests/__snapshots__/test_renault_vehicle.ambr
- tests/fixtures.py
- tests/fixtures/kamereon/vehicle_action/horn-lights.horn.json
- tests/fixtures/kamereon/vehicle_action/horn-lights.lights.json
- tests/test_renault_vehicle.py
Is the current method acceptable and which types/tests/other things do I need to add?
> Add start-horn and start-lights methods to vehicle

- src/renault_api/kamereon/models.py
- tests/__snapshots__/test_renault_vehicle.ambr
- tests/cli/__snapshots__/test_vehicle.ambr
Added endpoints support for XCB1VE model (Megane E-Tech)
Fixes: #1718
> Megane E-Tech support (XCB1VE)
